### ISSUE TITLE
Payments not working 

### ISSUE THREAD

**Issue by thrisha24** [Jawwad-Fida/HealthStack-System#507]
If I click on checkout it's showing reverse not found. And I have not created .env files, is that necessary to create?

**Comment by Jawwad-Fida** [comment]
Yes
.env files are where your credentials are being stored.
We used a payment gateway local to our country, so the payment may not necessary work wherever you are.
However, the code may help you out if you want to implement a payment system in your application as well

**Comment by thrisha24** [comment]
Do I need to create .env file , even if I run the project in localhost?

**Comment by thrisha24** [comment]
Should I create .env files If I run in my localhoat? is that necessary?
